---
title: "Полугруппы, моноиды. Начала абстрактной алгебры"
author: "Юрченков Иван Александрович"
date: "25 02 2022"
output: 
  html_document: 
    toc: yes
    highlight: haddock
    theme: readable
    fig_width: 8
    fig_height: 8
    fig_caption: yes
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Алгебраические структуры

**Алгебраическая структура** -- множество элементов (носитель) $G$, с заданным на нем множеством операций (сигнатура), удовлетворяющим некоторой системе аксиом. Понятие алгебраической структуры является специальным понятием для обозначения понятия универсальной алгебры.

Здесь $n$-арная операция $\{*\}$ на $G$ -- это отображение прямого произведения $n$ экземпляров множества самого в себя (замкнутость носителя относительно сигнатуры).

Также алгебраические структуры в литературе именуют *группоидами*, *магмами*

Среди алгебраических структур выделяют следующие виды:

-   Квазигруппа -- непустая магма, в которой всегда возможно деление

-   Полугруппа $(S, *)$ -- непустая магма с ассоциативной операцией

-   Лупа (петля) -- квазигруппа с нейтральным элементом

-   Моноид -- полугруппа с нейтральным элементом

-   Группа -- моноид с обратным элементом во множестве

-   Абелева группа -- группа с свойством коммутативности для заданной на группе операции

-   Полукольцо

-   Кольцо

-   Коммутативное кольцо

-   Целостное кольцо

-   Тело

-   Поле

-   Модуль над кольцом

-   Решётка

-   Идеал

-   и т.д.

Существует понятие **морфизма** алгебраических структур. **Морфизм** -- это функция (отображение) $f:S \rightarrow T$, где $S, T$ -- это алгебраические структуры со своей бинарной операцией, которую мы обозначим $*_S$ и $*_T$ соответственно. Тогда

$$
    \forall x, y \in S: f(x\  {*_S}\  y) = f(x)\  {*_T}\  f(y)
$$ говорят, что **морфизм** $f$ сохраняет бинарную операцию.

## Полугруппа

### Определение

**Полугруппа** -- алгебраическая структура с заданным множеством $S$ и с заданной на нем бинарной операцией $\{*\}$: $(S, {*})$, а также удовлетворяющее одной аксиоме:

A1: **Ассоциативность** $\forall a, b, c \in S: a*b*c = (a * b) * c = a* (b*c) \in S$

### Примеры полугрупп

1.  Множество натуральных чисел $\mathbf{N}$ относительно операции сложения $\{+\}$. Исследуем данную структуру:

Пусть $a, b, c \in \mathbf{N}$. Тогда выполняется что $a + b + c = (a + b) + c = a + (b + c) \in \mathbf{N}$ по правилу сложения натуральных чисел. Поскольку $a, b, c > 0$ и операция сложения данных чисел не выводит нас за пределы множества.

2.  Множество натуральных чисел $\mathbf{N}$ относительно операции умножения $\{\cdot\}$. Исследуем данную структуру:

Пусть $a, b, c \in \mathbf{N}$. Тогда выполняется что $a \cdot b \cdot c = (a \cdot b) \cdot c = a \cdot (b \cdot c) \in \mathbf{N}$ по правилу умножения натуральных чисел. Поскольку $a, b, c > 0$ и операция умножения данных чисел не выводит нас за пределы множества.

3.  Множество рациональных чисел $\mathbf{Q}$ относительно операции умножения.

### Итоги

Полугруппа это очень широкий и богатый класс структур, ввиду малого ограничения на данную классификацию. В дальнейшем мы будем видеть ситуации в которых полугруппы так же могут быть и структурами, отвечающими более серьезным ограничениям и аксиомам на групповую операцию.

## Моноид

### Определение

**Моноид** -- алгебраическая структура с заданным множеством $\mathbf{M}$ и с заданной на нем бинарной операцией $(\mathbf{M}, \{*\})$, а также удовлетворяющее двум аксиомам:

A1: **Ассоциативность**. $\forall a, b, c \in M: a*b*c = (a * b) * c = a* (b*c) \in M$

A2: **Наличие единичного (нейтрального) элемента**. $\exists ! e \in \mathbf{M}: \forall a \in \mathbf{M}: a * e = e * a = a \in \mathbf{M}$.

**Моноид** -- полугруппа, удовлетворяющая аксиоме А2.

*Нейтральный элемент* $e$ часто называют единицей по аналогии с умножением чисел:

$$
    \forall a \in \mathbf{R}: a\cdot 1 = 1 \cdot a = a \in \mathbf{R}
$$

### Примеры моноидов

1.  Множество натруальных чисел с нулём $\mathbf{N} \cup \{0\}$ относительно операции сложения $\{+\}$. Исследуем данную структуру $(\mathbf{N} \cup \{0\}, +)$:

-   Проверим аксиому А1. Пусть $\forall a,b,c \in \mathbf{N} \cup \{0\}$, тогда $a + b + c = (a + b) + c = a + (b + c) \in \mathbf{N} \cup \{0\}$ ввиду правила сложения неотрицательных целых чисел.

-   Проверим аксиому А2. Ввиду того, что $\exists ! 0\in \mathbf{N} \cup \{0\}$, то $\forall a \in \mathbf{N} \cup \{0\}: 0 + a = a + 0 = a \in \mathbf{N} \cup \{0\}$ ввиду правила сложения неотрицательных целых чисел.

ч.т.д.

2.  Множество натуральных чисел $\mathbf{N}$ относительно операции умножения $\{\cdot\}$. Исследуем данную структуру $(\mathbf{N}, \cdot)$:

-   Проверим аксиому А1. Пусть $\forall a,b,c \in \mathbf{N}$, тогда $a \cdot b \cdot c = (a \cdot b) \cdot c = a \cdot (b \cdot c) \in \mathbf{N}$ ввиду правила умножения натуральных чисел.

-   Проверим аксиому А2. Ввиду того, что $\exists ! 1\in \mathbf{N}$, то $\forall a \in \mathbf{N}: 1 \cdot a = a \cdot 1 = a \in \mathbf{N}$ ввиду правила умножения натуральных чисел.

ч.т.д.

3.  Множество натуральных чисел $\mathbf{N}$ относительно операции $HOK(a, b)$. Исследуем данную структуру $(\mathbf{N}, НОК)$:

-   Проверим аксиому А1. Пусть $\forall a,b,c \in \mathbf{N}$, тогда $HOK(a, b, c) = HOK(a, HOK(b, c)) = HOK(HOK(a, b), c) \in \mathbf{N}$, потому что $HOK(a, b, c) \ge a,\ HOK(a, b, c) \ge b,\ HOK(a, b, c) \ge c$.

-   Проверим аксиому A2. Ввиду того, что $\exists ! 1 \in \mathbf{N}: \forall a \in \mathbf{N}: НОК({a}, 1) = НОК(1, a) = a$.

ч.т.д.

4.  Множество действительных чисел с плюс бесконечностью $\mathbf{R} \cup \{+\infty\}$ относительно операции минимума $min(a, b)$.

5.  Множество действительных чисел с минус бесконечностью $\mathbf{R} \cup \{-\infty\}$ относительно операции максимума $max(a, b)$.

6.  Подмножества некоторого множества относительно операции объединения.

### Итоги

Моноиды -- класс структур, имеющий достаточную представленность относительно реальных прикладных классов алгебр, однако со все ещё маленькой аксиоматикой для фиксации важных теоретико-групповых свойств.

## Группа

### Определение

**Группа** -- алгебраическая структура с заданным множеством $G$ и бинарной операцией на нем $\{\circ \}$: $(G, \{\circ\})$, а также удовлетворяющая трем аксиомам:

A1: **Ассоциативность**. $\forall a,b,c \in G: a \circ b \circ c = (a \circ b) \circ c = a \circ (b \circ c) \in G$

A2: **Существование нейтрального элемента**. $\exists ! e \in G: \forall a \in G: e \circ a = a\circ e = a \in G$/

A3: **Существование обратного элемента**. $\forall a\in G: \exists! a^{-1} \in G: a\circ a^{-1} = e \in G$

**Группа** -- моноид, для которого выполнена аксиома существования обратного элемента А3.

### Примеры групп

1.  Поэлементное сложение $n$-мерных векторов $V = \{\overline{v_i} = (x_1^i, x_2^i, \dots ,x_n^i)| x_j^i \in \mathbf{R};\  j = \overline{1, n}\}$ заданной длины -- $(V, \{+\})$.

-   Действие группы на элементы -- смещение в $n$-мерном пространстве радиус-вектора материальной точки на заданные координаты другого такого же вектора. Из определения операции следует выполнение аксиомы А1 в силу свойств движения тел в $n$-мерном Евклидовом пространстве.

-   В данном примере существует нейтральный элемент -- начало координат или отсутсвие движения $e = (0, 0, \dots 0) \in V$, что удовлетворяет аксиоме А2.

-   Обратный элемент для каждого элемента группы это движение назад на предыдущую точку в пространстве $\forall a = (a_1, a_2, \dots, a_n) \in V: \exists! a^{-1} = (-a_1, -a_2, \dots, -a_n): a + a^{-1} = e \in V$.

ч.т.д.

Данная группа является примером **бесконечной группы**.

2.  Группа вычетов по модулю 5 относительно операции сложения:

|       | 0   | 1   | 2   | 3   | 4   |
|-------|-----|-----|-----|-----|-----|
| **0** |  0  | 1   | 2   | 3   | 4   |
| **1** |  1  | 2   | 3   | 4   | 0   |
| **2** |  2  | 3   | 4   | 0   | 1   |
| **3** |  3  | 4   | 0   | 1   | 2   |
| **4** | 4   | 0   | 1   | 2   | 3   |

: Таблица сложения вычетов по модулю 5

Представленная таблица для примера называется таблицей Кэли. Данная таблица передает все групповые свойства и аксиомы **конечной группы**. В результате таблица Кэли получила широкое упоминание при изучении теории конечных групп.

## Задания

**Задание №1**. Докажите что множество рациональных чисел $\mathbf{Q}$ относительно операции сложения $\{+\}$ является полугруппой.

**Задание №2**. Докажите что множество $\mathbf{R} \cup \{+\infty \}$ относительно операции $min(a, b)$ является моноидом.

**Задание №3**. Докажите что множество $\{True, False\}$ относительно операции $\cap$ является моноидом.

**Задание №4**. Рассмотрите множество положений вершин прямоугольника относительно операции поворота на 90 градусов относительно центра. Покажите отношение к одной из показанных ранее алгебраических структур. Постройте таблицу Кэли для данного множества с операцией.
