---
title: "Евклидовы кольца. Расширенный алгоритм Евклида"
author: "Юрченков Иван Александрович"
date: "05 04 2022"
output: html_document
---

# **Евклидовы кольца**

## Определение

**Евклидово кольцо** --- общеалгебраическое кольцо, в котором существует аналог алгоритма Евклида.

**Евклидово кольцо** -- целостное кольцо (*область целостности*) с единицей $R = <M, \{+, \cdot\}>$, для которой определена евклидова норма $d: R \rightarrow N\cup \{0\}$ такая, что возможно деление с остатком по норме меньшим делителя, то есть $\forall a, b \in R, b\ne 0$ имеется представление $a = b\cdot q + r$, для которого $d(r) < d(q)$ или $r = 0$.

## Смежное определение (подробное)

Коммутативное кольцо $R$ называется **евклидовым**, если для него выполнены следующие свойства:

А1: Кольцо $R$ является целостным

А2: Задана норма $d: R \rightarrow \mathbb{N} \cup \{0\}$ такая, что $d(r) = 0 \leftrightarrow r = 0$

А3: Вводится деление с остатком на число (делитель), в котором остаток по норме $d$ не превышает делитель:

$$
\forall a, b \in R, \ \ b\ne 0 \ \ \exists q, r \in R \\
a = b \cdot q + r, \ \ \ d(r) < d(b) 
$$ A4: Вводится правило нормировки по произведению:

$$
\forall a, b \in R, \ a\ne 0, \ b \ne 0\\
d(ab) \ge max(d(a), d(b))
$$ норма произведения двух чисел из кольца не меньше нормы каждого числа в отдельности.

Все эти аксиомы нужны для того, чтобы организовать работающую версию деления с остатком с необходимым перечнем аксиом и свойств для реализации расширенной версии алгоритма Евклида.

## Свойства

Евклидово кольцо $R$ является:

-   целостным

-   кольцом с единицей

-   кольцом главных идеалов (произвольный идеал -- главный)

## Примеры

-   **Кольцо целых чисел** ${\displaystyle \mathbb {Z} }$ . Пример евклидовой функции --- абсолютная величина ${\displaystyle |\cdot |}$.

Кольцо является целостным (не имеет делителей нуля), т.к. является числовым кольцом.

На кольце задана норма: $|\cdot|: \mathbb{Z} \rightarrow \mathbb{N} \cup \{0\}$ -- модуль числа.

Для любого целого числа существует деление с остатком, не превышающем делитель:

$$
5 \{3\} = 3 \cdot 1 + 2 \\
3 \{17\} = 17 \cdot 0  + 3 \\
-12 \{9\} = 9 \cdot (-2) + 6 \\
-3 \{6\} = 6 \cdot (-1) + 3
$$

Произведение чисел (не нулевых) по модулю не меньше максимума модуля чисел:

$$
|5| = 5, \ \ \ |-7| = 7 \ \ \ \\
|5 * (-7)| = 35 > |-7| > |5| \\
\ \\
|5 \cdot 1| \ge |5| > |1|
$$

-   Кольцо целых гауссовых чисел ${\displaystyle \mathbb {Z} [i]}$ (где ${\displaystyle i}$ --- мнимая единица, ${\displaystyle i^{2}=-1}$) с нормой ${\displaystyle d(a+ib)=a^{2}+b^{2}}$ --- евклидово.

$$
Z[i]: h(i) = a_0 + a_1 \cdot i + a_2 \cdot i^2 + \dots + a_{2n - 1} \cdot i^{2n-1} + a_{2n} \cdot i^{2n} = \\
= \sum_{i = 0, 2, \dots, 2n} \left( (-1)^{\frac{i}{2}} \cdot a_i \right) + i \cdot \sum_{j = 1, 3, \dots, 2n-1}^{} ((-1)^{\frac{j-1}{2}} \cdot a_j) = a + i\cdot b
$$

-   Произвольное поле ${\displaystyle K}$ является евклидовым кольцом с нормой, равной $1$ для всех элементов, кроме $0$.

-   Кольцо многочленов в одной переменной ${\displaystyle K[x]}$ над полем ${\displaystyle K}$. Пример евклидовой функции --- степень $T(f(x))$:

$$
T(f(x)) = \left\{ \begin{matrix} 0, &f = 0&  \\
                   deg(f(x)) + 1,  &f\ne 0&
            \end{matrix} \right.
$$

-   Евклидовым является кольцо конечных десятичных дробей, так как оно является кольцом частных кольца целых чисел ${\displaystyle \mathbb {Z} }$.

## Доказательство свойств

### *Евклидово кольцо является целостным*

$$
\forall r \in R \ \ \ d(r) = 0 \leftrightarrow r = 0\\
\forall r \in R \ \ \ r\ne 0 \ \ \ d(r) > 0 \\
\forall a,b \in R \ \ \ \ a \ne 0, b\ne 0 \\
d(ab) \ge max(d(a), d(b)) \\
\ \\
a,b \ne 0, \ \ a \cdot b = 0 \\
0 = d(0) = d(ab) \ge max(d(a), d(b)) > 0 \\
\ \\
0 > 0, \text{ противоречие}
$$

### *Евклидово кольцо является кольцом с единицей*

$$
\forall r \in R \ \ 1\cdot r = r \cdot 1 = r\\
\ \\
d: R \rightarrow \mathbb{N}\cup \{0\} \ \ \ \ d(r) = 0 \leftrightarrow r = 0 \\
\ \\
e^{'} -- \text{ элемент с наименьшей ненулевой нормой }\\
\ \\
e^{'} \ne 0 \rightarrow e^{'} = e^{'} \cdot e + r \ \ d(r) < d(e^{'}) \rightarrow r = 0 \\
\ \\
e^{'} = e^{'} \cdot e, \ \ \ \ \ a(b - c) = ab - ac\ (*) \\
\ \\
t \in R: \ \ e^{'} \cdot t = e \cdot e^{'} \cdot t \rightarrow e^{'} \cdot t - e^{'} \cdot e \cdot t = 0 \rightarrow \\
\rightarrow e^{'} (t - e\cdot t) = 0 \\
\ \\
e^{'} \ne 0 \\
t - e\cdot t = 0 \cdot t = e \cdot t
$$

### *Евклидово кольцо -- кольцо главных идеалов*

$$
(a) = \{a\cdot r\ |\ r\in R \} \\
I \text{ - идеал в } R \\
\ \\
b \in I: \begin{matrix} d(b) \ne 0 (b\ne 0) \\ 
                        d(b) \text{ - наименьший ненул.} \end{matrix} \\
\ \\
\forall t \in I: t = b \cdot q + r \ \ \ d(r) < d(b) \\
\ \\
b \in I \rightarrow b\cdot q \in I \rightarrow r = t - b\cdot q, \ r\in I \\
\ \\
\forall r \in R, \ \ b \cdot r \in I
$$

# **Расширенный алгоритм Евклида**

## Постановка задачи

Решить уравнение вида: $ax + by = НОД(a, b)$, где $a, b, x, y$ -- элементы евклидова кольца $R$.

## Пример

$$
R = \mathbb{Z}, \ a = 612, \ b = 342\\
\ \\
612 = 342 \cdot 1 + 270, \ или \ 270 = 612 - 342 \cdot 1, \\
340 = 270 \cdot 1 + 72, \ или \ 72 = 342 - 270 \cdot 1, \\ 
270 = 72 \cdot 3 + 54, \ или \ 54 = 270 - 72 \cdot 3, \\
72 = 54 \cdot 1 + 18, \ или \ 18  = 72 - 54 \cdot 1, \\
54 = 18 \cdot 3
$$

То есть 18 является наибольшим общим делителем. Решить уравнение: $612x + 342y = 18$

**Решить уравнение**.

$$612x + 342y = 18$$

Проведем вычисления в обратном порядке

$$
18 = 72 - 54 \cdot 1 = \\
= (342 - 270) - (270 - 72 \cdot 3) =  \\
= (342 - 270) - (270 - (342 - 270)\ cdot 3) =  \\
= 342 \cdot 4 - 270 \cdot 5  = \\
= 342 \cdot 4 - (612 - 342) \cdot 5 = \\
\ \\
= 342 \cdot 9 + 612 \cdot (-5) = 18 \\
\ \\
x = -5, \ \  y = 9
$$

## Общая схема алгоритма

$$
612 = 342 \cdot 1 + 270, \ или \ 270 = 612 - 342 \cdot 1, \\
340 = 270 \cdot 1 + 72, \ или \ 72 = 342 - 270 \cdot 1, \\ 
270 = 72 \cdot 3 + 54, \ или \ 54 = 270 - 72 \cdot 3, \\
72 = 54 \cdot 1 + 18, \ или \ 18  = 72 - 54 \cdot 1, \\
54 = 18 \cdot 3,\  или \  0 = 54 - 18 \cdot 3\\
\ \\
a_0 = a, \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \ \  \ \ \ \ \ \ \ \ \ \ \  \  a_0 = ax_0 + by_0 \\
a_1 = b, \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ a_1 = ax_1 + by_1  \\
a_2 = a_0 - a_1 \cdot q_1, \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ a_2 = ax_2 + by_2 \\
\dots \\
a_i = a_{i-2} - a_{i-1} \cdot q_{i-1},  \ \ \ \ \ a_i = ax_i + by_i\\
\dots \\
a_k = a_{k-2} - a_{k-1} \cdot q_{k-1}, \ \ \ \ \ a_k = ax_k + by_k\\
0 = a_{k-1} - a_{k} \cdot q_{k},\ \ \ \ \ \ \ \ \ \ \ \ 0 = ax_{k+1} + by_{k+1}
$$

$$
x_0 = 1, y_0 = 0 \\
x_1 = 0, y_1 = 1 \\
a_i = a_{i-2} - a_{i-1}q_{i-1}, \\
x_i = x_{i-2} - x_{i-1}q_{i-1}, \\
x_i = y_{i-2} - y_{i-1}q_{i-1}, \\
\ \\
или\ по\ схеме\\
\ \\
a_{i+2} = a_i - a_{i+1}q_{i+1}, \ \ a_{i} = ax_i + by_i, \\
x_{i+2} = x_i - x_{i+1}q_{i+1}, \ \ y_{i+2} = y_i - y_{i+1}q_{i+1}
$$

| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$  |0  |612|342|1  |0  |
|$\ 1$  |1  |342|270|0  |1  |
|2  |1  |270|72 |1  |-1 |
|3  |3  |72 |54 |-1 |2  |
|4  |1  |54 |18 |4  |-7 |
|5  |3  |18 |0  |-5 |9  |

: Таблица расширенного алгоритма Евклида


## Подробный пример работы расширенного алгоритма Евклида

### Постановка задачи

**Решить уравнение**. 

$$
ax + by = НОД(a, b)\\
a = 1146,\  b = 744
$$

### Прямой проход

Для решения данного уравнения, для начала, необходимо найти $НОД(a, b)$ для заданных из условия $a = 1146, \ b = 744$. Для этого необходимо воспользоваться алгоритмом Евклида:

| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|1  |0  |
|$\ 1$|   |  | |   |   |
|2  |   | |  |   |  |
|3  |   |  |   |   |   |
|4  |   |  |   |   |   |
|5  |   |  |   |   |   |
|6  |   |  |   |   |   |
|7  |   |  |   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 0

---------------------------------

$$
a_0 = 1146, \ b_0 = 744 \\
a_0 = b_0\cdot q_0 + r_0 \\
1146 = 744 \cdot 1 + (1146 - 744 \cdot 1)\\
1146 = 744 \cdot 1 + 402 \\
откуда \\
q_0 = 1, \ r_0 = 402 = a_1
$$

| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|  |  |
|$\ 1$|1  | 744 | 402 |   |   |
|2  |   | |  |   |  |
|3  |   |  |   |   |   |
|4  |   |  |   |   |   |
|5  |   |  |   |   |   |
|6  |   |  |   |   |   |
|7  |   |  |   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 1

---------------------------------


$$
744 > 402 \\
a_1 = 744,\ b_1 = 402\\
a_1 = b_1 \cdot q_1 + r_1 \\
744 = 402 \cdot 1 + (744 - 402 \cdot 1)\\
744 = 402 \cdot 1 + 342 \\
откуда\\
q_1 = 1,\ r_1 = 342 = a_2
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|  |  |
|$\ 1$|1  | 744 | 402 |   |   |
|2  |1  | 402 | 342  |   |  |
|3  |   |  |   |   |   |
|4  |   |  |   |   |   |
|5  |   |  |   |   |   |
|6  |   |  |   |   |   |
|7  |   |  |   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 2

---------------------------------


$$
402 > 342 \\
a_2 = 402,\ b_2 = 342\\
a_2 = b_2 \cdot q_2 + r_2 \\
402 = 342 \cdot 1 + (402 - 342 \cdot 1)\\
402 = 342 \cdot 1 + 60 \\
откуда\\
q_2 = 1,\ r_2 = 60 = a_3
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|  |  |
|$\ 1$|1  | 744 | 402 |   |   |
|2  |1  |402 | 342  |   |  |
|3  |1  |342 |60  |   |   |
|4  |   |  |   |   |   |
|5  |   |  |   |   |   |
|6  |   |  |   |   |   |
|7  |   |  |   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 3


---------------------------------


$$
342 > 60 \\
a_3 = 342,\ b_3 = 60\\
a_3 = b_3 \cdot q_3 + r_3 \\
342 = 60 \cdot 5 + (342 - 60 \cdot 5)\\
342 = 60 \cdot 5 + 42\\
откуда\\
q_3 = 5,\ r_3 = 42 = a_4
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|  |  |
|$\ 1$|1  | 744 | 402 |   |   |
|2  |1  |402 | 342  |   |  |
|3  |1  |342 |60  |   |   |
|4  |5  |60  |42   |   |   |
|5  |   |  |   |   |   |
|6  |   |  |   |   |   |
|7  |   |  |   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 4

---------------------------------


$$
60 > 42 \\
a_4 = 60,\ b_4 = 42\\
a_4 = b_4 \cdot q_4 + r_4 \\
60 = 42 \cdot 1 + (60 - 42 \cdot 1)\\
60 = 42 \cdot 1 + 18\\
откуда\\
q_4 = 1,\ r_4 = 18 = a_5
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|  |  |
|$\ 1$|1  | 744 | 402 |   |   |
|2  |1  |402 | 342  |   |  |
|3  |1  |342 |60  |   |   |
|4  |5  |60  |42   |   |   |
|5  |1  |42  |18   |   |   |
|6  |   |  |   |   |   |
|7  |   |  |   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 5

---------------------------------


$$
42 > 18 \\
a_5 = 42,\ b_5 = 18\\
a_5 = b_5 \cdot q_5 + r_5 \\
42 = 18 \cdot 2 + (42 - 18 \cdot 2)\\
42 = 18 \cdot 2 + 6\\
откуда\\
q_5 = 2,\ r_5 = 6 = a_6
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|  |  |
|$\ 1$|1  | 744 | 402 |   |   |
|2  |1  |402 | 342  |   |  |
|3  |1  |342 |60  |   |   |
|4  |5  |60  |42   |   |   |
|5  |1  |42  |18   |   |   |
|6  |2  |18  |6   |   |   |
|7  |   |  |   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 6

---------------------------------


$$
18 > 6 \\
a_6 = 18,\ b_6 = 6\\
a_6 = b_6 \cdot q_6 + r_6 \\
18 = 6 \cdot 3 + (18 - 6 \cdot 3)\\
18 = 6 \cdot 3 + 0\\
откуда\\
q_6 = 3,\ r_6 = 0 = a_7
$$

| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|  |  |
|$\ 1$|1  | 744 | 402 |   |   |
|2  |1  |402 | 342  |   |  |
|3  |1  |342 |60  |   |   |
|4  |5  |60  |42   |   |   |
|5  |1  |42  |18   |   |   |
|6  |2  |18  |6   |   |   |
|7  |3  |6  |0   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 7


---------------------------------


Итого, в результате на 7-ом шаге алгоритма Евклида находим решение $НОД(a, b)$ для заданных $a = 1146, \ b = 744$. и наибольший общий делитель равен $b_6 = 6$

### Решение уравнения

Исходя из постановки задачи и решения алгоритма Евклида получаем постановку задачи в следующем виде.

Решить уравнение:

$$
ax + by = НОД(a, b)\\
a = 1146,\ b = 744, \ НОД(a, b) = 6\\
\ \\
1146 x + 744y = 6
$$

Получаем Диофантово уравнение, которое необходимо решить в целых числах относительно $x$ и $y$

Для его решения составим таблицу исходя из заданных условий:

$$
a_{i} = a_{i-2} - a_{i-1}q_{i-1}, поскольку \\
a_{i-2} > a_{i-1} > a_{i}, где\\
a_{i-2} = a,\ a_{i-1} = b,\ q_{i-1} = q, \ a_{i} = r, \ для \ деления \ a\{b\} \ с \ остатком. 
$$


Тогда $x$ и $y$ на каждом шаге ищем в виде:

$$
x_{i+2} = x_{i} - x_{i+1}q_{i+1}\\
y_{i+2} = y_{i} - y_{i+1}q_{i+1}\\
при \ начальных \ условиях \\
x_0 = 1, \ y_0 = 0,\ т.к. \ a_0 = a = a \cdot 1 + b \cdot 0 = a \cdot x_0 + b \cdot y_0 , \\
x_1 = 0, \ y_1 = 1,\ т.к. \ a_1 = b = a \cdot 0 + b \cdot 1 = a \cdot x_1 + b \cdot y_1
$$

| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|1 | 0 |
|$\ 1$|1  | 744 | 402 | 0  | 1  |
|2  |1  |402 | 342  |   |  |
|3  |1  |342 |60  |   |   |
|4  |5  |60  |42   |   |   |
|5  |1  |42  |18   |   |   |
|6  |2  |18  |6   |   |   |
|7  |3  |6  |0   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 8

Тогда при помощи итерационной зависимости по шагам проведем поиск $x$ и $y$ -- решений уравнения:


---------------------------------

$$
x_2 = x_0 - x_1 \cdot q_1 =  1 - 0 \cdot 1 = 1\\
y_2 = y_0 - y_1 \cdot q_1 = 0 - 1 \cdot 1 = -1
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|1 | 0 |
|$\ 1$|1  | 744 | 402 | 0  | 1  |
|2  |1  |402 | 342  | 1  | -1 |
|3  |1  |342 |60  |   |   |
|4  |5  |60  |42   |   |   |
|5  |1  |42  |18   |   |   |
|6  |2  |18  |6   |   |   |
|7  |3  |6  |0   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 9

---------------------------------


$$
x_3 = x_1 - x_2 \cdot q_2 = 0 - 1 \cdot 1 = -1 \\
y_3 = y_1 - y_2 \cdot q_2 = 1 - (-1) \cdot 1 = 2
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|1 | 0 |
|$\ 1$|1  | 744 | 402 | 0  | 1  |
|2  |1  |402 | 342  | 1  | -1 |
|3  |1  |342 |60  | -1 | 2 |
|4  |5  |60  |42   |   |   |
|5  |1  |42  |18   |   |   |
|6  |2  |18  |6   |   |   |
|7  |3  |6  |0   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 10


---------------------------------

$$
x_4 = x_2 - x_3 \cdot q_3 = 1 - (-1) \cdot 1 = 2\\
y_4 = y_2 - y_3 \cdot q_3 = -1 - 2 \cdot 1 = -3
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|1 | 0 |
|$\ 1$|1  | 744 | 402 | 0  | 1  |
|2  |1  |402 | 342  | 1  | -1 |
|3  |1  |342 |60  | -1 | 2 |
|4  |5  |60  |42   | 2 | -3 |
|5  |1  |42  |18   |   |   |
|6  |2  |18  |6   |   |   |
|7  |3  |6  |0   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 11


---------------------------------

$$
x_5 = x_3 - x_4 \cdot q_4 = -1 - 2\cdot 5 = -11\\
y_5 = y_3 - y_4 \cdot q_4 = 2 - (-3) \cdot 5 = 17
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|1 | 0 |
|$\ 1$|1  | 744 | 402 | 0  | 1  |
|2  |1  |402 | 342  | 1  | -1 |
|3  |1  |342 |60  | -1 | 2 |
|4  |5  |60  |42   | 2 | -3 |
|5  |1  |42  |18   | -11  | 17  |
|6  |2  |18  |6   |   |   |
|7  |3  |6  |0   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 12


---------------------------------------

$$
x_6 = x_4 - x_5 \cdot q_5 =  2 - (-11) \cdot 1 = 13\\
y_6 = y_4 - y_5 \cdot q_5 = -3 - 17 \cdot 1 = -20
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|1 | 0 |
|$\ 1$|1  | 744 | 402 | 0  | 1  |
|2  |1  |402 | 342  | 1  | -1 |
|3  |1  |342 |60  | -1 | 2 |
|4  |5  |60  |42   | 2 | -3 |
|5  |1  |42  |18   | -11  | 17  |
|6  |2  |18  |6   | 13  | -20  |
|7  |3  |6  |0   |   |   |

: Таблица расширенного алгоритма Евклида, шаг 13


---------------------------------

$$
x_7 = x_5 - x_6 \cdot q_6 = -11 - 13 \cdot 2 = -37\\
y_7 = y_5 - y_6 \cdot q_6 = 17 - (-20) \cdot 2 = 57
$$


| i |$q_i$|$a_i$|$a_{i+1}$|$x_i$|$y_i$|
|---|---|---|---|---|---|
|$\ 0$ |--  |1146|744|1 | 0 |
|$\ 1$|1  | 744 | 402 | 0  | 1  |
|2  |1  |402 | 342  | 1  | -1 |
|3  |1  |342 |60  | -1 | 2 |
|4  |5  |60  |42   | 2 | -3 |
|5  |1  |42  |18   | -11  | 17  |
|6  |2  |18  |6   | 13  | -20  |
|7  |3  |6  |0   |  -37 | 57  |

: Таблица расширенного алгоритма Евклида, шаг 14

--------------------------------

Тогда $x = -37$ и $y = 57$.

