---
title: "Практическое занятие №10. Общее решение задачи расширенного алгоритма Евклида в евклидовых кольцах. Гомоморфизмы колец. Поля"
author: "Юрченков Иван Александрович"
date: "11 04 2022"
output:
  html_document: 
    toc: yes
  word_document: default
---

# **Общее решение задачи расширенного алгоритма Евклида**

## **Постановка задачи**

Решить уравнение вида: 

$$
a\cdot x + b\cdot y = НОД(a, b), \ \ \forall a, b, x, y \in R_E,
$$ 
где $R_E$ -- евклидово кольцо. 

Пусть $d = НОД(a, b)$, тогда $a = d \cdot a^{*}$ и $b = d \cdot b^{*}$, где $a^{*}$ и $b^{*}$ взаимно просты.

Тогда без потери общности, можем переписать уравнение в виде:

$$
d \cdot a^{*} \cdot x + d \cdot b^{*} \cdot y = d.
$$

Если данное равенство, в пределах действий над евклидовым кольцом, с двух сторон сложить с обратным к $d$ в группе кольца по сложению, а именно элементом $(-d)$, тогда получим:

$$
d \cdot a^{*} \cdot x + d \cdot b^{*} \cdot y + (-d) = d + (-d)  = 0,
$$

$$
d \cdot a^{*} \cdot x + d \cdot b^{*} \cdot y + (-d) = 0.
$$

В полученном нами равенстве по свойству дистрибутивности умножения слева на элемент кольца, а также беря во внимание, что евклидово кольцо -- *кольцо с единицей* и для него верно, что $(-d) = \underset{d}{-1 -1 -\dots -1} =d \cdot (-1)$, вынесем налево элемент $d$ как сомножитель:

$$
d \cdot (a^{*} \cdot x + b^{*} \cdot y - 1) = 0, \ \ d \ne 0.
$$

Так как евклидово кольцо $R_E$ является целостным, то в нем нет элементов -- делителей нуля, поэтому один из сомножителей обязан равняться нулю по свойству кольца $k \cdot 0 = 0, \ \forall k \in R$. Так как элемент $d = НОД(a, b), \ \forall a, b \in R_E$, то $d \ne 0$, и следовательно нулю может быть равен только сомножитель $a^{*} \cdot x + b^{*} \cdot y - 1 = 0$.

Тогда прибавим к обеим частям равенства:
$$
a^{*} \cdot x + b^{*} \cdot y - 1 = 0
$$
нейтральный по умножению в $R_E$, получим:

$$
a^{*} \cdot x + b^{*} \cdot y = 1.
$$

Пусть исходя из расширенного алгоритма Евклида мы найдем пару решений для изначальной постановки задачи $\exists\  x^{*}, y^{*}: a \cdot x^{*} + b \cdot y^{*} = d$, тогда при заданном условии на $a = d \cdot a^{*}$ и $b = d \cdot b^{*}$ можно утверждать, что:

$$
a \cdot x^{*} + b \cdot y^{*} = d,
$$

$$
d \cdot a^{*} \cdot x^{*} + d \cdot b^{*} \cdot y^{*} = d,
$$

$$
d \cdot a^{*} \cdot x^{*} + d \cdot b^{*} \cdot y^{*} - d = 0,
$$


$$
d \cdot (a^{*} \cdot x^{*} + b^{*} \cdot y^{*} - 1) = 0, \ \ d\ne 0,
$$

$$
a^{*} \cdot x^{*} + b^{*} \cdot y^{*} = 1,
$$
найденные корни $x^{*}$ и $y^{*}$ также являются решением и данного равенства.

Получаем систему решений:

$$
\left\{ \begin{matrix} a^{*} \cdot x^{*} + b^{*} \cdot y^{*} = 1, \\a^{*} \cdot x + b^{*} \cdot y = 1. \end{matrix} \right.
$$

Вычтем из первого равенства второе поэлементно (прибавим обратный к элементам в равенстве) и по аксиоме о дистрибутивности получим:

$$
a^{*} \cdot (x - x^{*}) + b^{*} \cdot (y - y^{*}) = 0
$$
и по свойству кольца получаем, что серия решений $(y - y^{*})$  обязана быть кратна $(y - y^{*})\  \vdots\  a^{*}$, и симметрично $(x - x^{*}) \ \vdots \ b^{*}$ (из-за того, что сумма двух элементов дает нейтральный по сложению в $R_E$).

Получаем:

$$
x = x^{*} + t \cdot b,\ \ t \in R_E,
$$

$$
y = y^{*} - t \cdot a^{*},\ \ t \in R_E,
$$
где $x(t), y(t) \in R_E$ -- полученная пара серии общего решения уравнения $a \cdot x + b \cdot y = НОД(a, b), \ \ x, y, a, b \in R_E$.
 
## **Пример**

Заданы следующие условия задачи:
$$
a \cdot x + b \cdot y = d = НОД(a, b),
$$

$$
a = 612,\ b = 342,\ d = 18.
$$

Тогда найдем пару нормированных коэффициентов:
$$
a^{*} = \frac{642}{18} = 34, \ \ b^{*} = \frac{342}{18} = 19.
$$

Из решения расширенным алгоритмом Евклида получим:
$$
x^{*} = -5, \ \ y^{*} = 9.
$$

Получим ответ в виде серии решений:

$$
x = x + t\cdot b^{*} = -5 + t \cdot 19; \ \ 
y = y - t\cdot b^{*} = 9 - t \cdot 34;
$$
где $t \in  R_E$ -- произвольный элемент евклидова кольца.

# **Отображения в кольцах**

## **Определение**

**Гомоморфизм колец**. Отображение $\varphi: R \rightarrow R^{'}$, где $R = <M, \{+, \cdot\}>$ и $R^{'} = <M^{'}, \{\oplus, \odot \}>$ -- два кольца, называется гомоморфизмом, если:

$$
\forall a, b \in R:\  \varphi(a + b) = \varphi(a) \oplus \varphi(b),
$$

$$
\forall a, b \in R:\  \varphi(a \cdot b) = \varphi(a) \odot \varphi(b).
$$

Если более детально, то гомоморфизм колец переводит групповую операцию сложения двух элементов в кольце в операцию сложения отображений в другом кольце. И то же самое происходит с операцией умножения в кольце. 

Примечательно, что в результате отображения операция умножения не сохраняет свои свойства в изначальном кольце, ровно как и свойство кольца не отображаются в новое, поскольку прообраз и образ -- разные алгебраические структуры.

**Изоморфизм колец**. Изоморфизмом называют взаимно однозначный гомоморфизм колец. 

В изоморфизме примечательно сохранение свойств умножения колец ровно как и свойств самих колец ввиду однозначной обратимости данного отображения.

## **Свойства**

1. Образ кольца $\varphi(R) = Im(R)$ является кольцом. 

- Стоит принять во внимание, что **образом кольца** называется множество элементов, нашедшие свое место в новом кольце в результате гомоморфизма: $Im(R) = \{\ \varphi(a) \in R^{'} \ | \ a \in R  \}$.

2. Гомоморфизм колец задает гомоморфизм между их группами по сложению.

- Логичным является тот факт, что даже если отображение ничего не делает со свойствами группы по сложению, так как кольца выстраиваются на коммутативных Абелевых группах, то все равно не все элементы являются однозначно обратимыми, в следствие чего однозначного обратного отображения обозначить между кольцами невозможно.

3. Композиция гомоморфизмов -- гомоморфизм.

## **Ядро гомоморфизма колец**

**Утверждение**. Ядро любого гомоморфизма колец является двусторонним идеалом.

**Ядро гомоморфизма колец** -- множество элементов кольца-прообраза, ставшие нейтральными элементами кольца-образа по сложению в результате гомоморфизма колец:

$$
Ker(\varphi) = \{a \in R \ |\  \varphi(a) = 0_{R^{'}}  \}.
$$

**Доказательство**. 

Гомоморфизм колец задает гомоморфизм между их группами по сложению, следовательно ядро является подгруппой по сложению. 

$$
Ker(\varphi) = \{x\ |\ x\in R,\  \varphi(x) = 0\}
$$

$$
\forall a \in R, \ \   \forall x\in Ker(\varphi): \varphi(a \cdot x) = \varphi(a) \cdot \varphi(x) = \varphi(a) \cdot 0 = 0 \in Ker(\varphi)
$$

$$
\forall a \in R, \ \   \forall x\in Ker(\varphi): \varphi(x \cdot a) = \varphi(x) \cdot \varphi(a) = 0 \cdot \varphi(a) = 0 \in Ker(\varphi)
$$

**ч.т.д.**


# **Поля**

## **Определение поля**

**Полем** называется множество $M$ с заданным на нем двумя алгебраическими операциями, которые обозначают $+$ и $\cdot$ (сложение и умножение соответственно) и тремя аксиомами:

А1: Поле является коммутативной группой по сложению.

- Данная аксиома напрямую наследуется от первой аксиомы колец.

А2: Ненулевые элементы $M^{*} = M \backslash \{0\}$ поля образуют коммутативную группу по умножению.

- Данная аксиома является расширением аксиомы кольца по ассоциативности умножения до определения абелевой группы по умножению на носитель (элементы множества) поля, без нейтрального по сложению, как алгебраической структуры.

А3: Аксиома дистрибутивности: $\forall a, b, c \in M: \ \ (a + b) \cdot c = c \cdot (a + b) = a\cdot c + b \cdot c.$

- В следствие коммутативности операции умножения аксиома дистрибутивности более не нуждается в различии между порядками следования операций сложения и умножения.

Стоит обратить внимание также на то, что в поле также как и в кольце нейтральный элемент по сложению также присутствует и обозначается "$0$". Нейтральный элемент по умножению также присутсвует как и в кольце с единицей и обозначается как "$1$".

Поле обозначается точно так же как и другие ранее показанные алгебраические структуры с двумя заданными операциями на них:

$$
F = <M, \{+, \cdot\}>
$$

## **Характеристика поля**

**Характеристикой поля** называется порядок единицы (нейтрального элемента по умножению) в коммутативной группе поля. Вспоминая определение порядка элемента коммутативной группы, данный термин можно обозначить в более удобном виде:

$$
char(F) = \left\{ \begin{matrix} m \in \mathbb{N}: 1 + 1 + \dots + 1 = m\ 1 = 0. \\
                            0, \text{ если } \ m = \infty    \end{matrix} \right.
$$

То есть *характеристика поля* -- число применений $m$ операции сложения к нейтральному элементу группы поля по умножению для достижения им нейтрального элемента по сложению. Если такое $m$ найти невозможно, то характеристика равна $char(F) = 0$.

--------------------------------------------------------

**NB**.

- Если порядок $1$ в аддитивной группе поля $F$ конечен, то его называют *характеристикой поля* $char(F)$.

- Если порядок $1$ в аддитивной группе поля $F$ бесконечен, то *характеристика поля* $char(F) = 0$.

--------------------------------------------------------

Характеристика поля является важным числом для поля, и его значение может быть не любым при конечном порядке нейтрального элемента по умножению:

--------------------------------------------------------

**Утверждение**. Если $char(F) \ne 0$, тогда $char(F) = p$, где $p$ -- простое число. 

--------------------------------------------------------

**Доказательство**. 

Возьмем нейтральный элемент по умножению $1$ и применим к нему $m$ раз операцию сложения.

$$
\underset{m}{(1 + 1 + \dots + 1)} = 0
$$

Предположим, что $m$ не является простым. Если оно не является простым, тогда $m$ раскладывается на множители.

$$
m = t \cdot k, \ \ t\ne 1, k\ne 1 \in \mathbb{N}.
$$

$$
\underset{t}{(1 + 1 + \dots + 1)} \cdot \underset{k}{(1 + 1 + \dots + 1)} = 0
$$

Если раскрыть скобки, мы получим ровно $m$ единиц, так что с отношением между операциями в таком резком переходе проблем не возникает.

$$
\underset{t}{(1 + 1 + \dots + 1)} \cdot \underset{k}{(1 + 1 + \dots + 1)} = \underset{m}{(1 + 1 + \dots + 1)} = 0
$$

Поскольку поле это кольцо, а также поле удовлетворяет трем аксиомам групп по умножению, значит каждый элемент кроме нуля обратим по умножению, следовательно делителей нуля в данном множестве нет. Поэтому, одно из чисел $t$ или $k$ обязано быть нулём. 

То есть либо $t$ единиц в сумме дают ноль, либо $k$ единиц в сумме дают ноль, что противоречит определению порядка, так как $t < m$ и $k < m$, а **порядок элемента группы** $m$ -- наименьшее натуральное число количества применений групповой операции к элементу группы.

**ч.т.д.**

## **Свойства полей**

1. Если поле имеет ненулевую характеристику, то характеристика является простым числом.

2. Поле является кольцом.

3. В поле всегда разрешимо уравнение: $a \cdot x + b = 0,\ \ \  a\ne 0$.

(Прибавить к обеим частям элемент обратный $b$ и домножить обе части на элемент обратный $a$ по умножению)

4. В поле всего два идеала: само поле и $\{0\}$.

Из предположения, что в идеале находится один ненулевой элемент, следует, что в идеале находится все поле.

5. В каждом поле есть подполе, изоморфное $\mathbb{Q}$ или $\mathbb{Z}_p$, где $p$ -- простое число.

6. В поле $F$ с характеристикой $char(F) = p$ отображение $x \rightarrow x^p$ является автоморфизмом данного поля -- отображением поля в самого себя.

## **Автоморфизм Фробениуса**

**Утверждение**.В поле $F$ с характеристикой $char(F) = p$ отображение $x \rightarrow x^p$ является автоморфизмом данного поля -- отображением поля в самого себя.

1. Автоморфизм Фробениуса -- гомоморфизм.

Рассмотрим данное отображение относительно двух элементов поля и покажем, что данное отображение является гомоморфизмом. Для этого необходимо показать сохранение операций сложения и умножения при переходе в другое поле:

$$
\forall a, b \in F
$$

$$
\varphi(a + b) = \varphi(a) + \varphi(b)
$$

$$
\varphi(a \cdot b) = \varphi(a) \cdot \varphi(b)
$$

Из коммутативности поля по умножению, второе условие доказывается элементарно:

$$
(a\cdot b)^p = a^p \cdot b^p,
$$
тогда как со вторым уловием необходимо разобраться более детально. 

Рассмотрим сумму элементов в степени:

$$
(a + b)^p = \sum_{k=0}^{p}C_p^k a^k b^{p-k}
$$


$$
C_p^0 = C_p^p = 1
$$

$$
C_p^k = \left( \frac{p!}{k! \ (p - k)!} \right) \  \vdots \  p, \ k\ne 0, \ k\ne p
$$

Стоит обратить внимание, на то, что коэффициент перед $a^{k} \cdot b ^{p - k}$ а именно $C_p^k = \left( \frac{p!}{k! \ (p - k)!} \right)$ является натуральным по свойству сочетаний и также делится на $p$, так как числитель содержит $p$, и знаменатель не делится на  $k$. Поэтому данный коэффициент стоит раcценивать как количество применений групповой операции сложения элементов кольца $a^{k} \cdot b ^{p - k}$.

Поскольку количество применений групповой операции сложения выполняется $C_p^k$ раз, а сам коэффициент $C_p^k = \left( \frac{p!}{k! \ (p - k)!} \right)$ по итогу делится нацело на $p$: $C_p^k = \left( \frac{p!}{k! \ (p - k)!} \right) \ \vdots \ p$, где $p$ -- простое число и характеристика поля $char(F) = p$, то сам коэффициент выполняет роль показателя количества раз применений подряд $p$ раз применения сложения к элементу поля. Это означает, что коэффициенты $C_p^k$ приводят элементы $a^{k} \cdot b ^{p - k}$ к нейтральному по сложению, то есть нулю. Тогда:

$$
(a + b)^p = \sum_{k=0}^{p}C_p^k a^k b^{p-k} = a^p + b^p
$$

2. Ядро автоморфизма Фробениуса -- содержит один элемент.

Для того, чтобы показать что доказанный гомоморфизм является изоморфизмом, необходимо показать, что данный гомоморфизм имеет нулевое ядро, или что существует биекция между элементами полей при отображении.

Нулевое ядро обозначает, что нейтральный элемент первого поля отображается в нейтральный элемент по сложению другого поля в результате отображения и никакой другой элемент поля-прообраза не отображается в нейтральный по сложению: $Ker(\varphi) = \{0_R\}.$

По свойству идеалов поля, идеалов у произвольного поля всего два: нулевой элемент и всё поле. По свойству гомоморфизма кольца -- ядро гомоморфизма кольца является идеалом. 

Раз единица поля при отображении не отображается в ноль, значит в результате гомоморфизма идеал порождает поле по структуре исходного поля по свойству втягивания. Следовательно ядро гомоморфизма -- идеал, равный исходному полю, из чего следует что данный гомоморфизм является автоморфизмом данного поля.

**ч.т.д.**



## **Примеры полей**

1. Действительные числа $\mathbb{R}$ относительно операции сложения и умножения.

2. Рациональные числа $\mathbb{Q}$ относительно операции сложения и умножения.

3. Комплексные числа $\mathbb{C}$ относительно операции сложения и умножения.

4. *Алгебраические числа* $\mathbb{A}$ над полем рациональных чисел.

5. Числа вида ${\displaystyle a+b{\sqrt {2}}}$, ${\displaystyle a,b\in \mathbb {Q} }$, относительно обычных операций сложения и умножения. Это один из примеров квадратичного поля, которое образует подполе в ${\displaystyle \mathbb {R} }$.

6. Арифметика по простому модулю: $\mathbb{Z}_p$ относительно операции сложения и умножения по модулю $p$, где $p$ -- простое число.

