---
title: "Практика Юрченков Иван Александрович"
output: 
  word_document: 
    toc: yes
    fig_width: 8
    fig_height: 8
    fig_caption: yes
---


**Исходное интегральное уравнение.** Рассмотрим следующий класс задач нестационарной акустики. В ограниченной трёхмерной области $Q$, окружённой свободным пространством, материальная среда характеризуется индексом рефракции $n(x), x ∈ Q$, а вне $Q$ индекс рефракции равен единице. Требуется определить акустическое поле в пространстве $\mathbb{R}^3$, порождаемое внешним источником $f_0(x, t)$, локализованным в конечной области, причём $f_0(x, t)=0$ при $t < 0$. В такой постановке соответствующая математическая задача формулируется следующим образом: найти функцию акустического поля $U(x, t)$ в $\mathbb{R}^3$, удовлетворяющую волновому уравнению

$$
ΔU(x, t) − \frac{n(x)}{c^2} \frac{∂^2U(x, t)}{∂t^2} = f_0(x, t),  \ \ \ \ \ \ \ \ \ \  (1)
$$


где $c$ – скорость звука в свободном пространстве. К уравнению (1) необходимо добавить ещё условия, гарантирующие отсутствие волн, приходящих из бесконечности.


Для вывода нестационарных интегральных уравнений будем использовать прямое и обратное преобразования Фурье:


$$
f(ω) = F[f(t)] = \int_{−∞}^{+∞} f(t)e^{iωt} dt, \ \  f(t) = F^{−1}[f(ω)] = \frac{1}{2π} \int_{−∞}^{+∞} f(ω)e^{−iωt} dω. \ \ \ (2)
$$

В формулах (2) исходная функция $f(t)$ и её фурье-образ $f(ω)$ различаются указанием аргументов $t$ и $ω$ соответственно.

Применяя преобразование Фурье к каждой части уравнения (1), получаем уравнение для фурье-образов поля


$$
ΔU(x, \omega) − \frac{n(x) \omega^2}{c^2} U(x, \omega) = f_0(x, \omega), \ \ \ \ \ (3)
$$


Фурье-образ $U(x, ω)$ должен удовлетворять, кроме уравнения (3), ещё и условию излучения на бесконечности

$$
\underset{r \rightarrow \infty}{lim} \left( r \left( \frac{\partial U}{\partial r} - i\frac{\omega}{c} U \right) \right) = 0, \ \ \ r = |x| = \sqrt{(x_1^2 + x_2^2 + x_3^2)}. \ \ \ \ \ (4)
$$

Пусть $f(x, ω)$ – финитная функция в $\mathbb{R}^3$ относительно $x$. Тогда интегральное представление


$$
V(x, \omega) = - \int f(y, \omega) G(R, \omega) dy \ \ \ \ \ \ \ (5)
$$


удовлетворяет в $\mathbb{R}^3$ уравнению Гельмгольца

$$
ΔV + \frac{\omega^2}{c^2}V = f \ \ \ \ \ \ \ \ (6) 
$$

и условию излучения на бесконечности вида (4). В (5) $G(R, ω)$ – функция Грина уравнения Гельмгольца, которая в декартовой системе координат имеет вид

$$
G(R, ω) = exp(iωR/c)/(4πR), \ \ \ R = |x − y|, \ \ \ x = (x_1, x_2, x_3), \ \ \  y = (y_1, y_2, y_3). \ \ \ \ (7)
$$


Запишем уравнение (3) в следующем виде:

$$
ΔU + (ω/c)^2U = f_0 − (ω/c)^2 (n − 1) U. \ \ \ \ \ (8)
$$


Из соотношений (3)–(8) вытекает, что неизвестное поле $U(x, ω)$ имеет следующее интегральное
представление:

$$
U(x, \omega) = - \int f_0(y, \omega) G(R, \omega)dy + \left( \frac{w^2}{c^2} \right) \int_Q \left( n(y) - 1 \right) U(y, \omega) G(R, \omega)dy, \ \ \  x \in \mathbb{R}^3 . \ \ \ \ \ \ (9)
$$


Первый интеграл в правой части равенства (9) описывает поле $U_0(x, ω)$, создаваемое источником $f_0(x, ω)$ в свободном пространстве. Далее, поскольку $n(x)=1$ вне $Q$, из равенства (9) следует, что неизвестное поле $U(x, ω)$ удовлетворяет в области $Q$ интегральному уравнению Фредгольма второго рода

$$
U(x, \omega) - \left( \frac{\omega^2}{c^2} \right) \int_Q \left( n(y) - 1 \right) U(y, \omega) G(R, \omega)dy = U_0(x, \omega), \ \ \ x\in Q.
$$

Зная поле $U(x, ω)$ в области $Q$, несложно найти поле в любой точке пространства, используя равенство (9).

Имеют место следующие свойства Фурье-преобразований:

$$
F^{−1}[−ω^2f(ω)] = \frac{d^2f(t)}{dt^2} , \ \ \ \ \ (10)
$$

$$
F^{-1}[f(\omega)g(\omega)] = \int_{-\infty}^{\infty} f(\tau)g(t-\tau)d\tau, \ \ \ F^{-1}[e^{i \omega \Delta}] = \delta(t - \Delta), \ \ \ \ \  (11)
$$

где $δ$ – дельта-функция Дирака, а $Δ$ – некоторая постоянная. Преобразование Фурье обобщённых функций определяется для класса $S^{'}$ так называемых обобщённых функций медленного роста – линейных непрерывных функционалов на пространстве $S$ основных функций, представляющем собой линейное подпространство пространства $C^∞(\mathbb{R})$, состоящее из функций, которые при $|x|→∞$ убывают вместе со всеми производными быстрее любой степени $|x|^{−1}$, с заданной в нём специальной сходимостью (см. [4, гл. II, $§$ 8.1]). Именно, преобразованием Фурье обобщённой функции $f ∈ S^{'}$ называется [4, гл. II, $§$ 9.2] обобщённая функция $F[f]$ такая, что $(F[f], ϕ)=(f,F[ϕ])$ для всех $ϕ ∈ S$. Несложно убедиться [4, гл. II, $§$ 9.2], что так определённое отображение $F$ переводит $S^{'}$ в $S^{'}$ и является линейным и непрерывным, а для обратного отображения $F^{−1}$ очевидно равенство $(F^{−1}[f], ϕ)=(f,F^{−1}[ϕ])$ для всех $ϕ ∈ S$.

В силу определений (2) равенство (10) очевидно. Покажем справедливость первого равенства в (11). Имеем

$$
F \left( \int_{-\infty}^{+\infty} f(\tau) g(t-\tau)d \tau \right) = \int_{-\infty}^{+\infty} e^{i \omega (t- \tau)} \left( \int_{-\infty}^{+\infty} f(\tau)g(t-\tau)d\tau \right) dt =
$$


$$
= \int_{-\infty}^{+\infty} f(\tau) e^{i\omega \tau} \left( \int_{-\infty}^{+\infty} e^{i \omega (t- \tau)} g(t - \tau) d(t-\tau) \right) d\tau = f(\omega) g(\omega) \ \ \ \ \ \ \  (12)
$$

Применяя обратное преобразование Фурье к первому и последнему членам в цепочке равенств (12), получаем первое равенство в (11). Доказательство второго равенства в (11) следует непосредственно из определения преобразования Фурье обобщённых функций и приведено, например, в [4, гл. II, $§$ 9.2, пример].

Из представления (7) и второго равенства в (11) вытекает, что

$$
F^{−1}[G(R, ω)] = (4πR)^{−1}δ(t − R/c).  \ \ \ \ \ \ \ (13)
$$


В силу соотношений (10)–(13) получаем

$$
F^{−1}[G(R, ω) ω^2 f(y, ω)] = −(4πR)^{−1} \left( \int_{−∞}^{+∞} δ(\tau − R/c) \frac{∂^2f(y, t − \tau)}{∂t^2}dτ \right) =
$$


$$
= −(4πR)^{−1} \frac{∂^2f(y, \tau)}{∂\tau^2}, \ \ \ τ = t − R/c. \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ (14) 
$$

Теперь, применяя обратное преобразование Фурье к уравнению (9) и используя равенство (14),
приходим к следующему объёмному интегральному уравнению с запаздыванием по времени:


$$
U(x, t) = U_0(x, t) − \frac{1}{4πc^2} \int_Q  \frac{1}{R} (n(y) − 1) \frac{∂^2U(y, τ)}{∂τ^2}dy,
$$

$$
R = |x − y|; \ \ \ \  τ = t − R/c; \ \ \ \ U(x, t)=0 \ \text{  при  }\  t < 0. \ \ \ \ \ (15)
$$

Из уравнения (15) очевидно, что акустическое поле в $\mathbb{R}^3$ зависит только от значений поля в области неоднородности $Q$. Поэтому (15) можно рассматривать как интегральное уравнение в $Q$.

Из изложенного выше следует

**Теорема.** *Пусть индекс рефракции акустического поля равен $n(x)$ в ограниченной области $Q ⊂ \mathbb{R}^3$ и единице вне этой области. Тогда акустическое поле $U$, порождаемое внешним полем $U_0$, описывается объёмным интегральным уравнением (15), содержащим запаздывание по времени, зависящее от пространственных переменных.*

**2. Метод решения.** Будем использовать метод коллокации для численного решения уравнения (15). Для этого в прямоугольной декартовой системе координат в $\mathbb{R}^3$ введём конечное множество точек – *сетку* – так, чтобы область $Q$ целиком находилась в прямоугольном параллелепипеде $Π$ со сторонами $N_lh$, $l = 1, 2, 3$, где $h$ – шаг сетки по декартовым координатам. Тогда если $x^0 = (x_1^0, x_2^0, x_3^0)$ – вершина этого параллелепипеда с наименьшей суммой координат, то координаты каждого узла сетки имеют вид $x^0 + (p_1h, p_2h, p_3h)$, где $p_l = \overline{0, N_l}$, l = 1, 2, 3,
т.е. вид x0 + hp, где p = (p1, p2, p3). Поэтому каждый узел однозначно определяется точкой
p = (p1, p2, p3), pl = 0, Nl, l = 1, 2, 3, которую назовём сеточными координатами узла и
будем писать p ∈ Q, если узел с сеточными координатами p лежит в области Q. Параллеле-
пипед Π разбивается данной сеткой на ячейки (элементарные кубики) Π(p), p = (p1, p2, p3),



