---
title: "Темы курсовых работ (дополнение)"
author: "Юрченков Иван Александрович"
date: "17 02 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Темы работ

1. Разработка Telegram бота

- 1.1. Разработка бота для формирования финансового портфеля

    Выбор интересующих котировок; Измерение корреляции выбранных котировок; Вывод графиков за выбранный период времени; Вывод трейд-маркеров для котировок; Прогнозирование цен на основе какого-либо алгоритма; 
    
[Ссылка на интересное Stackoverflow](https://stats.stackexchange.com/questions/8407/import-stock-price-from-yahoo-finance-into-r)
    

- 1.2. Разработка бота для подборки вакансий по ключевым словам

- 1.3. Разработка бота для информирования о погоде

- 1.4. Разработка бота для обработки изображений

2. Использование алгоритмов балансировки классификационных выборок. Oversampling или Smote. Алгоритм ADASYN. ASMO. SMOTENC. Алгоритм Метрополиса — Гастингса. Сэмплирование по Гиббсу

3. Алгоритм кластеризации клиентов в финансовой сфере.

4. Формирование признаков из слабоструктурированных данных. Использование векторизации признакового пространства в задачах статистического обучения.

5. Разработка backend части обработки данных на OLTP системе.


