---
title: "Практическое занятие №5. Введение в модулярную арифметику"
author: "Юрченков Иван Александрович"
date: "11 03 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Китайская теорема об остатках**


$$\forall i,j \in \mathbf{N}: i\ne j$$
$$\{n_j, b_j\}\in \mathbf{Z}: НОД(n_i, n_j) = 1$$

Справедливо

$$
\exists x \in \mathbf{Z} : \left\{ \begin{matrix}x = b_1\{n_1\} \\ x = b_2\{n_2\} \\ \cdots \\ x = b_m\{n_m\} \end{matrix} \right.
$$

### **Доказательство теоремы**

**Доказательство теоремы**

**Лемма**. Если $a$ и $b$ взаимно просты $(НОД(a, b) = 1)$, то найдется такое целое число $\exists c \in \mathbf{Z}$, что $a\cdot c \equiv 1\{b\}$

**Доказательство леммы**. Покажем, что: $a, 2a, \dots, (b - 1)a$ дают различные остатки при делении на $b$, отличные от $0$.

*Ни одно из этих чисел не делится на $b$, т.е. все они дают различные остатки, отличные от $0$.*

Действительно, если бы это было не так, то:

$$
    ai \equiv aj \{b\},
$$
для некоторых $i$, $j$ где $1 \le i \ne j \le b-1$.

Но тогда возникает проблема с тем, что $a(i - j) = ai - aj = 0\{b\}$. То есть $a(i-j)\  \vdots\  b$, что возможно если $(i - j)\ \vdots\  b$, так как $a$ и $b$ -- взаимно простые. Но $-b < i-j < b$, (так как $1 \le i, j \le b-1$) поэтому $i - j$ должно быть равно нулю, что неверно по нашему предположению.

Значит, все числа $a_i$ дают различные остатки при делении на $b$.

**NB**. В наборе $a, 2a, 3a, \dots, (b-1)a$ ровно $(b-1)$ чисел. Значит, все данные числа дают все возможные различные отличные от $0$ значения остатков при делении на $b$, то есть среди этих чисел есть число, дающее остаток $1$.

**Лемма доказана**.

Введем обозначения: $N = n_1\cdot n_2 \cdot \dots \cdot n_k$; $N_i = \frac{N}{n_i}$.

Определим из леммы: $x_i \in \mathbf{Z} \rightarrow x_i \cdot N_i \equiv 1\{n_i\}$; $НОД(N_i, n_i) = 1$.

Теперь мы можем написать явно формулу для $x$:

$$
x = r_1 \cdot x_1 \cdot N_1 + r_2\cdot x_2 \cdot N_2 + \dots + r_k \cdot x_k \cdot N_k.
$$

Докажем, что $x$ удовлетворяет требуемой системе. Для этого рассмотрим, например, число $x$ по модулю $n_i$: все слагаемые, начиная со второго, содержат множители $N_i$, которые по определению делятся на $n_1$, значит, 

$$
x = r_1 \cdot x_1 \cdot N_1 \{n_1\},
$$

а так как $x_1 \cdot N_1 = 1 \{n_1\}$, то $x \equiv r_1 \{n_1\}$. Таким образом мы доказали, что $M$ удовлетворяет первому уравнению.

Аналогично, можно убедиться, что $x$ удовлетворяет всей системе по очереди.

Теперь рассмотрим два решения системы $A$ и $B$, покажем, что $A \equiv B\{N\}$, так как 

$$
A - B = r_i - r_i \equiv 0\{n_i\}
$$ 
для $\forall i \in [1, k]$, то 

$$
A - B\  \vdots\  n_i.
$$  

Однако, нам известно, что числа $n_i$ попарно взаимно просты, поэтому $A - B \ \vdots\ N = n_1 \cdot n_2 \cdot \dots \cdot n_k$

**Теорема доказана**.

### **Пример**

Решить систему уравнений с помощью китайской теоремы об остатках

$$
\left\{
    \begin{matrix}
    x&\equiv& 2\{5\} \\
    x&\equiv& 15\{17\} \\
    x&\equiv& 5\{12\}
    \end{matrix}
\right.
$$
 
$x = (2, 15, 5)$, $p = (5, 17, 12)$, $N = 5 \cdot 17 \cdot 12 = 1020$
 
**Решение**

$$N = 1020$$
$$N_1 = 1020/5 = 204$$
$$N_2 = 1020/17 = 60$$
$$N_3 = 1020/12 = 85$$
$$(204 \cdot b_1)\ \%\ 5 \equiv 1 \rightarrow b_1 = (204\ \%\ 5)^{-1} \{5\} = 4^{-1}\{5\} \rightarrow b_1 = 4$$ 
$$(60 \cdot b_2)\ \%\ 17 \equiv 1 \rightarrow b_2 = (60\ \%\ 17)^{-1} \{17\} = 9^{-1}\{17\} \rightarrow b_2 = 2$$
$$(85 \cdot b_3)\ \%\ 12 \equiv 1 \rightarrow b_3 = (85\ \%\ 12)^{-1} \{12\} = 1^{-1}\{12\} \rightarrow b_3 = 1$$

$$x = (2, 15, 5) = (2 \cdot 204 \cdot 4 + 15 \cdot 60 \cdot 2 + 5 \cdot 85 \cdot 1)\ \%\ 1020 = $$
$$=(1632 + 1800 + 425) \ \%\ 1020 = (612 + 780 + 425)\ \%\ 1020 = 797\{1020\}$$

$$x(n) = 797 + 1020 \cdot n, \ \ \ n \in 0,1,2,\dots$$
 
## **Модулярная арифметика**

СОК -- система остаточных классов

Модулярная арифметика базируется на **"Китайской теореме об остатках"**.

-------------------------------------------------------------------

**Определение.** Для любой системы взаимно простых чисел $p_1, p_2, \dots, p_n$ любое число $x$ из диапазона $[0, M)$, где $M = p_1 \cdot p_2 \cdot \dots \cdot p_n$ взаимооднозначно представимо в виде вектора $(a_1, a_2, \dots, a_n)$, где $a_i = X\ \%\ p_i$ (здесь и далее $\%$ -- операция взятия остатка по модулю от целочисленного деления $X$ на $p_i$)

$p_1, p_2, \dots, p_n$ -- модули системы

$a_1, a_2, \dots, a_n$ -- остатки (вычеты) числа по заданной системе модулей

-------------------------------------------------------------------

## Свойства модулярной арифметики

### **1. Отсутствие переноса разрядов в сложении и умножении**
Пусть даны два числа $x_1$ и $x_2$, представимые в виде системы остатков $(x_{11}, x_{12}, \dots, x_{1n})$ и $(x_{21}, x_{22}, \dots, x_{2n})$ по системе взаимно простых чисел $(p_1, p_2, \dots , p_n)$. В этом случае:

$$
x_3 = x_1 + x_2 = ((x_{11} + x_{21})\ \%\ p_1, (x_{12} + x_{22})\ \%\ p_2, \dots, (x_{1n} + x_{2n})\ \%\ p_n)
$$

$$
x_3 = x_1 \cdot x_2 = ((x_{11} \cdot x_{21})\ \%\ p_1, (x_{12} \cdot x_{22})\ \%\ p_2, \dots, (x_{1n} \cdot x_{2n})\ \%\ p_n)
$$

То есть, чтобы сложить или умножить два числа, достаточно сложить или умножить соответствующие элементы вектора. Также возмножно это сделать параллельно и очень быстро из-за малых размерностей $x_{ij}$


### **2. Ошибка в одной позиции вектора не влияет на расчёты в других позициях вектора**

В отличие от позиционной системы счисления все элементы вектора равнозначны и ошибка в одном из них ведёт всего лишь к сокращению динамического диапазона. Этот факт позволяет проектировать устройства с повышенной отказоустойчивостью и коррекцией ошибок.


## Прямое преобразование

Прямое преобразование из позиционной системы счисления в систему счисления в остатках заключается в нахождении остатков от деления по каждому из модулей системы.

---------------------------------------------------------------------------

**Пример.** Пусть требуется найти представление числа $X = 25$ по системе модулей $(3, 5, 7)$, тогда  $X_p = (1, 0, 4)$.

Реализация нахождения вычета по заданному модулю строится на свойствах вычетов:

$$(a + b)\ \%\ p = (a\ \%\ p + b\ \%\ p)\ \%\ p $$

$$(a \cdot b)\ \%\ p = (a\ \%\ p \cdot b\ \%\ p)\ \%\ p $$

Любое число $X$, представленное в двоичной системе счисления, можно записать в виде

$$
    X\ \%\ p = (X_{n-1} \cdot 2^{n-1} + X_{n-2} \cdot 2^{n-2} + \dots + X_{0} \cdot 2^{0})\ \%\ p = 
    ((X_{n-1} \cdot 2^{n-1})\ \%\ p + (X_{n-2} \cdot 2^{n-2})\ \%\ p + \dots + (X_{0} \cdot 2^{0})\ \%\ p)\ \%\ p
$$

Поскольку в данном случае $X_{n-1}, X_{n-2},\dots,X_0$ равны $0$ или $1$, то фактически нам потребуется сложить вычеты вида $(2^{i}\ \%\ p)$

**Пример.** Пусть задано число $25$ или в двоичной системе счисления $11001$ и требуется найти остаток по модулю $7$:

$$
25\ \%\ 7 = (1 \cdot 2^4 + 1 \cdot 2^3 + 0\cdot 2^2 + 0\cdot 2^1 + 1 \cdot 2^0)\ \%\ 7 = 
(2^4\ \%\ 7 + 2^3\ \%\ 7 + 2^0 \ \%\ 7)\ \%\ 7 = (2 + 1 + 1)\ \%\ 7 = 4\ \{7\}
$$

---------------------------------------------------------------------------

## **Арифметические операции**

**Пример**: Пусть задана система модулей $(3, 5, 7)$, то есть мы можем выполнять операции, результат которых не превышает $3 * 5 * 7 = 105$. Умножим два числа $8$ и $10$.

$$
    8 = (8\ \%\ 3, 8\ \%\ 5, 8\ \%\ 7) = (2 \{3\}, 3 \{5\}, 1\{7\}) = (2, 3, 1)
$$

$$
 10 = (10\ \%\ 3, 10\ \%\ 5, 10\ \%\ 7) = (1 \{3\}, 0 \{5\}, 3\{7\}) = (1, 0, 3)
$$

$$
    8 \cdot 10 = ((2 \cdot 1)\ \%\ 3, (3 \cdot 0)\ \%\ 5, (3 \cdot 1)\ \%\ 7) = (2 \{3\}, 0 \{5\}, 3\{7\}) = (2, 0, 3)
$$

Проверяем:
$$
80 = (80\ \%\ 3, 80\ \%\ 5, 80\ \%\ 7) = (2\{3\}, 0\{5\}, 3\{7\}) = (2, 0 ,3)
$$

## **Обратное преобразование**

Обратное преобразование из системы счисления в остаточных классах в позиционную систему счисления производится одним из двух способов:

1. На базе Китайской теоремы об остатках или системы ортогональных базисов
2. На базе полиадического кода (система со смешанным основанием)

## Способ на основе КТО

Способ, основанный на Китайской теореме об остатках базируется на следующей идее:

$$
x = (x_1, x_2, \dots, x_n) = (x_1, 0, \dots, 0) + (0, x_2, \dots, 0) + \dots + (0 ,0, \dots, x_n) = 
$$
$$
=x_1 \cdot (1, 0, \dots, 0) + x_2 \cdot (0, x_2, \dots, 0) + \dots + x_n \cdot (0 , 0, \dots, 1)
$$

Таким образом, видим, что для обратного преобразования нам требуется найти систему ортогональных базисов $B_1 = (1, 0, \dots, 0);\ \  B_2 = (0, 1, \dots, 0);\ \dots \ B_n = (0, 0, \dots, 1)$. Данные вектора находятся один раз для заданного базиса, а для их поиска требуется решить уравнение вида:

$$
(M_i \cdot b_i)\ \%\ p_i = 1,
$$
где $M_i = \frac{M}{p_i}$; а $b_i$ -- искомое число. В этом случае позиционное представление можно переписать как:

$$
X= (x_1 \cdot (M_1 \cdot b_1) + x_2 \cdot (M_2 \cdot b_2) + \dots + x_n \cdot (M_n \cdot b_n))\ \%\ M
$$

**Пример.** Пусть задана система модулей $(3, 5, 7)$. Найдем значения $M_i$ и $b_i$ для $(0 < i \le 3)$:
$$M = 3 \cdot 5 \cdot 7 = 105$$
$$M_1 = 105/3 = 35$$
$$M_2 = 105/5 = 21$$
$$M_1 = 105/7 = 15$$
$$(M_1 \cdot b_1)\ \%\ 3 = 1 \rightarrow (35\ \%\ 3 \cdot b_1\ \%\ 3)\ \%\ 3 = 1 \rightarrow (2 \cdot b_1\{3\})\{3\} = 1{3} \rightarrow b_1 = 2$$
$$(M_2 \cdot b_2)\ \%\ 5 = 1 \rightarrow (21\ \%\ 5 \cdot b_2\ \%\ 5)\ \%\ 5 = 1 \rightarrow (1 \cdot b_2\{5\})\{5\} = 1{5} \rightarrow b_2 = 1$$
$$(M_3 \cdot b_3)\ \%\ 7 = 1 \rightarrow (15\ \%\ 7 \cdot b_3\ \%\ 7)\ \%\ 7 = 1 \rightarrow (1 \cdot b_3\{7\})\{7\} = 1{7} \rightarrow b_3 = 1$$

Теперь, преобразуем какое-нибудь число в системе остаточных классов. Положим:

$$
X = (2, 3, 1) = (2 \cdot 35 \cdot 2 + 3 \cdot 21 \cdot 1 + 1 \cdot 15 \cdot 1) \ \%\ 105 = 
$$
$$
=(140\ \%\ 105 + 63\{105\} + 15\{105\})\ \%\ 105 = (35 + 63 + 15)\ \%\ 105 = 113\ \%\ 105 = 8 \{105\}
$$


Минус данного метода заключается в том, что для обратного преобразования требуется умножение и сложение больших чисел $(M_1, M_2, \dots, M_n)$, а также операция взятия остатка по модулю большого числа $M$.

## **Способ на базе полиадического кода**.

Базируется на идее, что любое число $X$ может быть представлено в системе взаимнопростых чисел $p_1, p_2, \dots, p_n$ по принципу:

$$
X = a_1 + a_2 \cdot p_1 + a_3 \cdot p_1 \cdot p_2 + \dots + a_{n-1} \cdot p_1 \cdot p_2 \cdot \dots \cdot p_{n-2}, 
$$
где $0 < a_i < p_i$; 

$$x\{p_1\} = x_1 = a_1$$
$$
(x - a_1) \ \%\ p_2 = (x_2 - a_1) \%\ p_2 = (a_2 \cdot p_1)\ \%\ p_2 \rightarrow a_2 = ((p^{-1})\ \%\ p_2 \cdot (x_2 - a_1))\ \%\ p_2
$$

Для использования этого метода требуются константы вида: $(p_i^{-1}) \ \%\ p_k^{-1}$. Можно такде заметить, что начинать вычисление $a_3$ можно, как только появилось значение $a_1$. На основе этого метода можно строить конвеерные преобразователи.

**Пример**: $X = (2, 3, 1)$ и $p = (3, 5, 7)$

- $a_1 = x_1 = 2$

- $a_2 = ((p_1^{{-1}})\ \%\ p_2 \cdot (x_2 - a_1))\ \%\ p_2 = ((3^{-1})\ \%\ 5 \cdot (3 - 2))\ \%\ 5 = 2\cdot 1 = 2$

- $a_3 = ((p_2^{-1})\ \%\ p_3 \cdot ((p_1^{-1})\ \%\ p_3 \cdot (x_3 - a_1) - a_2))\ \%\ 7 = ((5^{-1})\ \%\ 7 \cdot ((3^{-1})\ \%\ 7 \cdot (1 - 2) - 2))\ \%\ 7 = (3 \cdot (5 \cdot (1 - 2) - 2))\{7\} = (3 \cdot (-7))\ \%\ 7 = 0$

$X = a_1 + a_2\cdot p_1 + a_3\cdot p_1 \cdot p_2 = a_1 + 3\cdot a_2 + 15\cdot a_3 = 2 + 3 \cdot 2 + 15 \cdot 0 = 8$

**Замечание.** Чтобы найти константы вида: $3^{-1}\ \%\ 5$ требуется решить уравнение $(3 \cdot x)\ \%\ 5 = 1$, где $0 \le x < 5$

